In [6]:
import pandas as pd

In [7]:
# 1. Create dataframe

df = pd.DataFrame([1,2,3])
print(df)

   0
0  1
1  2
2  3

In [8]:
df=pd.DataFrame([1,2,3],columns=["Numbers"])
print(df)

   Numbers
0        1
1        2
2        3

In [ ]:
df=pd.DataFrame([1,2,3],columns=["numbers"])
print(df)

   numbers
0        1
1        2
2        3
<class 'pandas.DataFrame'>

In [9]:
data={
    'name':['madhav','vidhi','nisha','vidhushi'],
    'age':[16,17,18,19],
    'salary':[90000,70000,50000,40000]
}
df=pd.DataFrame(data)
print(df)
print(type(df))

       name  age  salary
0    madhav   16   90000
1     vidhi   17   70000
2     nisha   18   50000
3  vidhushi   19   40000
<class 'pandas.DataFrame'>

In [19]:
# 2. Basic Data Frame understanding 
df.head(2) #top 2 rows print krega

     name  age  salary
0  madhav   16   90000
1   vidhi   17   70000

In [10]:
df.tail(2) #botton 2 rows print krega

       name  age  salary
2     nisha   18   50000
3  vidhushi   19   40000

In [ ]:
df.shape #no of rows and column print karega

Index(['name', 'age', 'salary'], dtype='str')

In [13]:
df.columns

Index(['name', 'age', 'salary'], dtype='str')

In [28]:
df.rename(columns={'salary':'Monthly_Salary'})

       name  age  Monthly_Salary
0    madhav   16           90000
1     vidhi   17           70000
2     nisha   18           50000
3  vidhushi   19           40000

In [22]:
df

       name  age  salary
0    madhav   16   90000
1     vidhi   17   70000
2     nisha   18   50000
3  vidhushi   19   40000

In [42]:
df.rename(columns={'age':'Student_age'},inplace=True)
df

       name  Student_age  salary
0    madhav           16   90000
1     vidhi           17   70000
2     nisha           18   50000
3  vidhushi           19   40000

In [40]:
df1=df.rename(columns={'name':'Student_name'})
df1

  Student_name  Student_age  salary
0       madhav           16   90000
1        vidhi           17   70000
2        nisha           18   50000
3     vidhushi           19   40000

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         4 non-null      str
 1   Student_age  4 non-null      int64
 2   salary       4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [45]:
df.describe()

       Student_age        salary
count     4.000000      4.000000
mean     17.500000  62500.000000
std       1.290994  22173.557826
min      16.000000  40000.000000
25%      16.750000  47500.000000
50%      17.500000  60000.000000
75%      18.250000  75000.000000
max      19.000000  90000.000000

In [46]:
#3. Save and Load data from csv file
df

       name  Student_age  salary
0    madhav           16   90000
1     vidhi           17   70000
2     nisha           18   50000
3  vidhushi           19   40000

In [47]:
df.to_csv('Test_data.csv')